### ISSUE TITLE
naive questions on the direction and goal of BA.jl

### ISSUE THREAD

**Issue by anandijain** [hildebrandtlab/BiochemicalAlgorithms.jl#41]
hey all! 

a long time go, i wrote a (private sadly) wrapper around PubChem and had some simple code for taking https://pubchem.ncbi.nlm.nih.gov/docs/pathways, using Groebner.jl to then balance the chemical reactions robustly. 
i might be allowed to rewrite in open source soon though

Then I would lower this to https://github.com/SciML/Catalyst.jl/ so that I could simulate the chemical reactions in the DiffEq ecosystem. 

I see that you guys have a nice wrapper around the PubChem API and was wondering what the directions for this project are.

One of my huge gripes about the models I work with from https://www.ebi.ac.uk/biomodels/ is they rarely have canonical IDs for species. My naive, highschool biology educated self thought that simulating glycolysis would be easy 😅 , luckily @Denis-Titov is making https://github.com/DenisTitovLab/Glycolysis.jl. 

anyways, a big thanks are in order, I plan to shift all of my pubchem related code like https://github.com/anandijain/ChemicalOfTheDay.jl to BA.jl. 

One other question I had is if you would consider splitting the API part of the package and the algorithms part.

also if you guys want to come to juliacon, we're doing a [symposium on systems biology](https://pretalx.com/juliacon2023/talk/review/XJYE7SFLZZXNN8CCS9HCNXEDH3ZSZGND) and I think standardizing on species database will be an important need for reproducible modeling in the future. 

if you guys want to give a short 5 minute talk, id be happy to try to work you in

**Comment by anhi** [comment]
Whoops - I'm really sorry for the awfully late reply. We somehow forgot to answer! Thank you for your kind words!

Essentially, we used to build BALL (https://github.com/BALL-Project/BALL.git) for years, but decided that it was time for a modern approach to structural bioinformatics and molecular modelling, and started moving to Julia. Our current plan is to get to feature parity with BALL and then extend from there, mostly towards combinations of machine learning and simulation approaches, for which Julia is ideally suited.

If you have any suggestions for future directions or functionality that would be important, please let us know!
